# Generated by Django 3.2.9 on 2024-10-15 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notion',
            old_name='content',
            new_name='sub_title',
        ),
    ]
