# Generated by Django 3.2.9 on 2024-10-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0002_rename_content_notion_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='notion',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
