# Generated by Django 3.2.9 on 2024-10-16 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0004_auto_20241016_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notion_cat',
            name='notion',
        ),
    ]
