# Generated by Django 3.2.9 on 2024-10-16 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0005_remove_notion_cat_notion'),
    ]

    operations = [
        migrations.AddField(
            model_name='notions',
            name='cat_notion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='notion.notion_cat'),
        ),
    ]
