# Generated by Django 3.2.9 on 2024-10-16 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0006_notions_cat_notion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notion_cat',
            new_name='NotionCat',
        ),
    ]
