# Generated by Django 3.2.9 on 2024-11-22 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0007_rename_notion_cat_notioncat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notioncat',
            options={'verbose_name': 'Категории', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='notions',
            options={'verbose_name': 'Мои заметки', 'verbose_name_plural': 'Мои заметки'},
        ),
        migrations.AddField(
            model_name='notions',
            name='fun_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='image_for_notion'),
        ),
        migrations.AlterField(
            model_name='notions',
            name='cat_notion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cat', to='notion.notioncat'),
        ),
    ]
